modLoader="javafml"
loaderVersion="[3,)"
license="MIT"
issueTrackerURL="https://github.com/Volwert123/more-food/issues"

[[mods]]
    modId="more_food"
    version="${version}"
    displayName="More Food"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/more-food-xd"
    logoFile="icon.png"
    authors="Volwert123, moritz_htk"
    description='''This mod adds more food to Minecraft.'''

[[dependencies.more_food]]
    modId="neoforge"
    type="required"
    versionRange="[20.6,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.more_food]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.more_food]]
    modId="architectury"
    type="required"
    versionRange="[12.1.3,)"
    ordering="AFTER"
    side="BOTH"

[modproperties.more_food]
    catalogueItemIcon="more_food:cooked_carrot"