modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://github.com/Volwert123/more-food/issues"

[[mods]]
    modId="more_food"
    version="${version}"
    displayName="More Food"
    updateJSONURL="https://api.modrinth.com/updates/more-food-xd/forge_updates.json?neoforge=only"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/more-food-xd"
    logoFile="assets/more_food/icon.png"
    authors="Volwert123, moritz_htk"
    description='''This mod adds more food to Minecraft.'''

[[dependencies.more_food]]
    modId="neoforge"
    type="required"
    versionRange="[21.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.more_food]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.more_food]]
    modId="architectury"
    type="required"
    versionRange="[16.0.3,)"
    ordering="AFTER"
    side="BOTH"

[modproperties.more_food]
    catalogueItemIcon="more_food:cooked_carrot"